### ISSUE TITLE
Installation wizard does not allow installation even if all licences are accepted.

### ISSUE THREAD

**Issue by koszyk** [microHAL/microIDE#17]
Using microIDE_setup_0.3.3_windows.exe
Selected user installation with custom components.
Accepting all licenses but still not able to go next.
![image](https://user-images.githubusercontent.com/3956344/39326381-166135c6-4995-11e8-85d1-795bd9e54f2b.png)

**Comment by sakoPO** [comment]
Problem is fixed in 0.3.4 release.
